name: SevenTwentySeven
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22462
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: SevenTwentySeven
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
