name: SevenTwentySeven
favicon: null
layout_spectrum: 0.4638445202726871
typography_spectrum: 0.8143613592255861
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6795064806938171
  lightness: 0.8108659621793777
  saturation: 0.8889864783268422
  rhythmicContrast: 0.5037319238763303
purpose: []
